/** @type {import('tailwindcss').Config} */
const animatePlugin = require("tailwindcss-animate");

module.exports = {
  darkMode: ["class"],
  content: [
    "./src/**/*.{ts,tsx}",
    "./src/**/*.css"
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        sm: 'var(--width-sm)',
        md: 'var(--width-md)',
        lg: 'var(--width-lg)',
        xl: 'var(--width-xl)',
        '2xl': 'var(--width-2xl)',
      },
    },
    extend: {
      colors: {
        // Base colors
        base: {
          black: 'rgb(var(--color-base-black))',
          white: 'rgb(var(--color-base-white))',
          transparent: 'rgb(var(--color-base-transparent))',
        },
        // Background colors
        bg: {
          primary: 'var(--color-brand-secondary-50)',
          secondary: 'var(--color-brand-primary-50)',
          tertiary: 'var(--color-brand-tertiary-50)',
          page: 'var(--color-brand-secondary-50)',
        },
        // Brand colors
        brand: {
          primary: {
            50: 'var(--color-brand-primary-50)',
            100: 'var(--color-brand-primary-100)',
            200: 'var(--color-brand-primary-200)',
            300: 'var(--color-brand-primary-300)',
            400: 'var(--color-brand-primary-400)',
            500: 'var(--color-brand-primary-500)',
            600: 'var(--color-brand-primary-600)',
            700: 'var(--color-brand-primary-700)',
            800: 'var(--color-brand-primary-800)',
            900: 'var(--color-brand-primary-900)',
            950: 'var(--color-brand-primary-950)',
          },
          secondary: {
            50: 'var(--color-brand-secondary-50)',
            100: 'var(--color-brand-secondary-100)',
            200: 'var(--color-brand-secondary-200)',
            300: 'var(--color-brand-secondary-300)',
            400: 'var(--color-brand-secondary-400)',
            500: 'var(--color-brand-secondary-500)',
            600: 'var(--color-brand-secondary-600)',
            700: 'var(--color-brand-secondary-700)',
            800: 'var(--color-brand-secondary-800)',
            900: 'var(--color-brand-secondary-900)',
            950: 'var(--color-brand-secondary-950)',
          },
          tertiary: {
            50: 'var(--color-brand-tertiary-50)',
            100: 'var(--color-brand-tertiary-100)',
            200: 'var(--color-brand-tertiary-200)',
            300: 'var(--color-brand-tertiary-300)',
            400: 'var(--color-brand-tertiary-400)',
            500: 'var(--color-brand-tertiary-500)',
            600: 'var(--color-brand-tertiary-600)',
            700: 'var(--color-brand-tertiary-700)',
            800: 'var(--color-brand-tertiary-800)',
            900: 'var(--color-brand-tertiary-900)',
            950: 'var(--color-brand-tertiary-950)',
          },
        },
        // UI colors
        ui: {
          success: {
            50: 'var(--color-ui-success-50)',
            100: 'var(--color-ui-success-100)',
            200: 'var(--color-ui-success-200)',
            300: 'var(--color-ui-success-300)',
            400: 'var(--color-ui-success-400)',
            500: 'var(--color-ui-success-500)',
            600: 'var(--color-ui-success-600)',
            700: 'var(--color-ui-success-700)',
            800: 'var(--color-ui-success-800)',
            900: 'var(--color-ui-success-900)',
            950: 'var(--color-ui-success-950)',
          },
          error: {
            50: 'var(--color-ui-error-50)',
            100: 'var(--color-ui-error-100)',
            200: 'var(--color-ui-error-200)',
            300: 'var(--color-ui-error-300)',
            400: 'var(--color-ui-error-400)',
            500: 'var(--color-ui-error-500)',
            600: 'var(--color-ui-error-600)',
            700: 'var(--color-ui-error-700)',
            800: 'var(--color-ui-error-800)',
            900: 'var(--color-ui-error-900)',
            950: 'var(--color-ui-error-950)',
          },
          warning: {
            50: 'var(--color-ui-warning-50)',
            100: 'var(--color-ui-warning-100)',
            200: 'var(--color-ui-warning-200)',
            300: 'var(--color-ui-warning-300)',
            400: 'var(--color-ui-warning-400)',
            500: 'var(--color-ui-warning-500)',
            600: 'var(--color-ui-warning-600)',
            700: 'var(--color-ui-warning-700)',
            800: 'var(--color-ui-warning-800)',
            900: 'var(--color-ui-warning-900)',
            950: 'var(--color-ui-warning-950)',
          },
          info: {
            50: 'var(--color-ui-info-50)',
            100: 'var(--color-ui-info-100)',
            200: 'var(--color-ui-info-200)',
            300: 'var(--color-ui-info-300)',
            400: 'var(--color-ui-info-400)',
            500: 'var(--color-ui-info-500)',
            600: 'var(--color-ui-info-600)',
            700: 'var(--color-ui-info-700)',
            800: 'var(--color-ui-info-800)',
            900: 'var(--color-ui-info-900)',
            950: 'var(--color-ui-info-950)',
          },
        },
        // Greyscale colors
        greyscale: {
          light: {
            50: 'var(--color-greyscale-light-50)',
            100: 'var(--color-greyscale-light-100)',
            200: 'var(--color-greyscale-light-200)',
            300: 'var(--color-greyscale-light-300)',
            400: 'var(--color-greyscale-light-400)',
            500: 'var(--color-greyscale-light-500)',
            600: 'var(--color-greyscale-light-600)',
            700: 'var(--color-greyscale-light-700)',
            800: 'var(--color-greyscale-light-800)',
            900: 'var(--color-greyscale-light-900)',
            950: 'var(--color-greyscale-light-950)',
          },
          dark: {
            50: 'var(--color-greyscale-dark-50)',
            100: 'var(--color-greyscale-dark-100)',
            200: 'var(--color-greyscale-dark-200)',
            300: 'var(--color-greyscale-dark-300)',
            400: 'var(--color-greyscale-dark-400)',
            500: 'var(--color-greyscale-dark-500)',
            600: 'var(--color-greyscale-dark-600)',
            700: 'var(--color-greyscale-dark-700)',
            800: 'var(--color-greyscale-dark-800)',
            900: 'var(--color-greyscale-dark-900)',
            950: 'var(--color-greyscale-dark-950)',
          },
        },
      },
      font: {
        display: 'var(--font-family-display)',
        heading: 'var(--font-family-heading)',
        body: 'var(--font-family-body)',
      },
      text: {
        xs: 'var(--font-size-xs)',
        sm: 'var(--font-size-sm)',
        base: 'var(--font-size-base)',
        lg: 'var(--font-size-lg)',
        xl: 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '4xl': 'var(--font-size-4xl)',
        '5xl': 'var(--font-size-5xl)',
        '6xl': 'var(--font-size-6xl)',
        '7xl': 'var(--font-size-7xl)',
        '8xl': 'var(--font-size-8xl)',
      },
      lineHeight: {
        1: 'var(--line-height-1)',
        2: 'var(--line-height-2)',
        3: 'var(--line-height-3)',
        4: 'var(--line-height-4)',
        5: 'var(--line-height-5)',
        6: 'var(--line-height-6)',
        7: 'var(--line-height-7)',
        8: 'var(--line-height-8)',
        9: 'var(--line-height-9)',
        10: 'var(--line-height-10)',
        11: 'var(--line-height-11)',
        12: 'var(--line-height-12)',
        13: 'var(--line-height-13)',
        14: 'var(--line-height-14)',
        15: 'var(--line-height-15)',
        16: 'var(--line-height-16)',
        17: 'var(--line-height-17)',
        18: 'var(--line-height-18)',
        19: 'var(--line-height-19)',
        20: 'var(--line-height-20)',
        21: 'var(--line-height-21)',
        22: 'var(--line-height-22)',
      },
      letterSpacing: {
        tighter: 'var(--letter-spacing-tighter)',
        tight: 'var(--letter-spacing-tight)', 
        normal: 'var(--letter-spacing-normal)',
        wide: 'var(--letter-spacing-wide)',
        wider: 'var(--letter-spacing-wider)',
      },
      
      spacing: {
        0: 'var(--spacing-0)',
        1: 'var(--spacing-1)',
        2: 'var(--spacing-2)',
        3: 'var(--spacing-3)',
        4: 'var(--spacing-4)',
        5: 'var(--spacing-5)',
        6: 'var(--spacing-6)',
        8: 'var(--spacing-8)',
        10: 'var(--spacing-10)',
        12: 'var(--spacing-12)',
        16: 'var(--spacing-16)',
        20: 'var(--spacing-20)',
        24: 'var(--spacing-24)',
        28: 'var(--spacing-28)',
        29: 'var(--spacing-29)',
        30: 'var(--spacing-30)',
        31: 'var(--spacing-31)',
        32: 'var(--spacing-32)',
        40: 'var(--spacing-40)',
        48: 'var(--spacing-48)',
        56: 'var(--spacing-56)',
        64: 'var(--spacing-64)',
      },

      margin: {
        'm-0': 'var(--spacing-0)',
        'm-2': 'var(--spacing-2)',
        'm-4': 'var(--spacing-4)',
        'm-6': 'var(--spacing-6)',
        'm-8': 'var(--spacing-8)',
      },

      marginLeft: {
        'ml-0': 'var(--spacing-0)',
        'ml-2': 'var(--spacing-2)',
        'ml-4': 'var(--spacing-4)',
        'ml-6': 'var(--spacing-6)',
        'ml-8': 'var(--spacing-8)',
      },

      marginRight: {
        'mr-0': 'var(--spacing-0)',
        'mr-2': 'var(--spacing-2)',
        'mr-4': 'var(--spacing-4)',
        'mr-6': 'var(--spacing-6)',
        'mr-8': 'var(--spacing-8)',
      },

      marginTop: {
        'mt-0': 'var(--spacing-0)',
        'mt-2': 'var(--spacing-2)',
        'mt-4': 'var(--spacing-4)',
        'mt-6': 'var(--spacing-6)',
        'mt-8': 'var(--spacing-8)',
      },

      marginBottom: {
        'mb-0': 'var(--spacing-0)',
        'mb-2': 'var(--spacing-2)',
        'mb-4': 'var(--spacing-4)',
        'mb-6': 'var(--spacing-6)',
        'mb-8': 'var(--spacing-8)',
      },

      padding: {
        'p-0': 'var(--spacing-0)',
        'p-1': 'var(--spacing-1)',
        'p-2': 'var(--spacing-2)',
        'p-3': 'var(--spacing-3)',
        'p-4': 'var(--spacing-4)',
        'p-5': 'var(--spacing-5)',
        'p-6': 'var(--spacing-6)',
        'p-8': 'var(--spacing-8)',
        'p-10': 'var(--spacing-10)',
        'p-12': 'var(--spacing-12)',
        'p-16': 'var(--spacing-16)',
        'p-20': 'var(--spacing-20)',
        'p-24': 'var(--spacing-24)',
        'p-28': 'var(--spacing-28)',
        'p-29': 'var(--spacing-29)',
        'p-30': 'var(--spacing-30)',
        'p-31': 'var(--spacing-31)',
        'p-32': 'var(--spacing-32)',
        'p-40': 'var(--spacing-40)',
      },
      borderWidth: {
        none: 'var(--border-width-none)',
        thin: 'var(--border-width-thin)',
        medium: 'var(--border-width-medium)',
        thick: 'var(--border-width-thick)',
      },
      borderRadius: {
        none: 'var(--border-radius-none)',
        sm: 'var(--border-radius-sm)',
        md: 'var(--border-radius-md)',
        lg: 'var(--border-radius-lg)',
        xl: 'var(--border-radius-xl)',
        '2xl': 'var(--border-radius-2xl)',
        full: 'var(--border-radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },

      width: {
        1: 'var(--width-1)',
        2: 'var(--width-2)',
        3: 'var(--width-3)',
        4: 'var(--width-4)',
        5: 'var(--width-5)',
        6: 'var(--width-6)',
        7: 'var(--width-7)',
        8: 'var(--width-8)',  
        10: 'var(--width-10)',
        12: 'var(--width-12)',
        13: 'var(--width-13)',
        14: 'var(--width-14)',
        16: 'var(--width-16)',
        20: 'var(--width-20)',
        24: 'var(--width-24)',
        28: 'var(--width-28)',
        32: 'var(--width-32)',
        40: 'var(--width-40)',
        48: 'var(--width-48)',
        56: 'var(--width-56)',
        64: 'var(--width-64)',
        72: 'var(--width-72)',
        80: 'var(--width-80)',
        96: 'var(--width-96)',
        100: 'var(--width-100)',
      },

      height: {
        '100vh': '100vh',
        '100svh': '100svh',
        1: 'var(--height-1)',
        2: 'var(--height-2)',
        3: 'var(--height-3)',
        4: 'var(--height-4)',
        5: 'var(--height-5)',
        6: 'var(--height-6)',
        7: 'var(--height-7)',
        8: 'var(--height-8)',
        9: 'var(--height-9)',
        10: 'var(--height-10)',
        11: 'var(--height-11)',
        12: 'var(--height-12)',
        13: 'var(--height-13)',
        14: 'var(--height-14)',
        15: 'var(--height-15)',
        16: 'var(--height-16)',
        17: 'var(--height-17)',
        18: 'var(--height-18)',
        19: 'var(--height-19)',
        20: 'var(--height-20)',
        21: 'var(--height-21)',
        22: 'var(--height-22)',
        24: 'var(--height-24)',
        28: 'var(--height-28)',
        32: 'var(--height-32)',
        36: 'var(--height-36)',
        40: 'var(--height-40)',
        44: 'var(--height-44)',
        48: 'var(--height-48)',
        52: 'var(--height-52)',
        56: 'var(--height-56)',
        60: 'var(--height-60)',
        64: 'var(--height-64)',
        72: 'var(--height-72)',
        80: 'var(--height-80)',
        96: 'var(--height-96)',
        112: 'var(--height-112)',
        128: 'var(--height-128)',
        144: 'var(--height-144)',
        160: 'var(--height-160)',
        176: 'var(--height-176)',
        192: 'var(--height-192)',
        208: 'var(--height-208)',
        224: 'var(--height-224)',
        240: 'var(--height-240)',
        256: 'var(--height-256)',
        272: 'var(--height-272)',
        288: 'var(--height-288)',
        304: 'var(--height-304)',
        320: 'var(--height-320)',
        336: 'var(--height-336)',
        352: 'var(--height-352)',
        368: 'var(--height-368)',
        384: 'var(--height-384)',
        400: 'var(--height-400)',
        416: 'var(--height-416)',
        432: 'var(--height-432)',
        448: 'var(--height-448)',
        464: 'var(--height-464)',
        480: 'var(--height-480)',
        496: 'var(--height-496)',
        512: 'var(--height-512)',
        528: 'var(--height-528)',
        544: 'var(--height-544)',
        560: 'var(--height-560)',
        576: 'var(--height-576)',
        592: 'var(--height-592)',
        608: 'var(--height-608)',
        624: 'var(--height-624)',
        640: 'var(--height-640)',
        656: 'var(--height-656)',
        672: 'var(--height-672)',
        688: 'var(--height-688)',
        704: 'var(--height-704)',
        720: 'var(--height-720)',
        736: 'var(--height-736)',
        752: 'var(--height-752)',
        768: 'var(--height-768)',
        784: 'var(--height-784)',
        800: 'var(--height-800)',
        816: 'var(--height-816)',
        832: 'var(--height-832)',
        848: 'var(--height-848)',
        864: 'var(--height-864)',
        880: 'var(--height-880)',
        896: 'var(--height-896)',
        912: 'var(--height-912)',
        928: 'var(--height-928)',
        944: 'var(--height-944)',
        960: 'var(--height-960)',
        976: 'var(--height-976)',
        992: 'var(--height-992)',
        1008: 'var(--height-1008)',
        1024: 'var(--height-1024)',
        1040: 'var(--height-1040)',
        1056: 'var(--height-1056)',
        1072: 'var(--height-1072)',
        1088: 'var(--height-1088)',
        1104: 'var(--height-1104)',
        1120: 'var(--height-1120)',
        1136: 'var(--height-1136)',
      },
    },
  },
  plugins: [animatePlugin],

}
